# Generated by Django 4.0.5 on 2022-08-28 15:38

import crm.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('linkedin', models.CharField(max_length=256)),
                ('add_contact', models.TextField()),
                ('group', models.CharField(max_length=20)),
                ('last_contact', models.DateField()),
                ('next_contact', models.DateField()),
                ('status', models.CharField(choices=[('Запрос отправлен', 'Request_send'), ('Отмена запроса', 'Request_cancel'), ('Повторный запрос', 'Repeated_request'), ('В контактах', 'In_contacts'), ('Не сейчас', 'Not_now'), ('Хочет узнать больше', 'More_info'), ('Готов созвониться', 'Ready_call'), ('Назначен звонок', 'Call_assigned'), ('Состоялся звонок', 'Phoned'), ('Сконвертирован', 'Converted'), ('Не целевая аудитория', 'Not_target_audience'), ('Не пишите мне больше', 'Not_write'), ('Удалил', 'Removed')], default=crm.models.Status['Request_send'], max_length=50)),
                ('step', models.CharField(choices=[('Поблагодарили за коннект', 'Thank_connect'), ('Отправили полезный контект', 'Useful_content'), ('Отправили опрос', 'Poll_deleted'), ('Отправили наш кейс', 'Sent_our_case'), ('Предложили созвониться', 'Suggested_call'), ('Пнули раз', 'Kicked_1'), ('Пнули два', 'Kicked_2'), ('Пнули на почту', 'Kicked_3_mail'), ('Повторно пнули на почту', 'Kicked_4_mail')], default=crm.models.LeadStep['Thank_connect'], max_length=50)),
                ('comment', models.TextField()),
                ('history', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
