# Generated by Django 4.0.5 on 2022-09-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_user_created_user_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('linkedin', models.CharField(max_length=256)),
                ('add_contact', models.TextField()),
                ('group', models.CharField(max_length=20)),
                ('last_contact', models.DateField()),
                ('next_contact', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('step', models.CharField(max_length=50)),
                ('history', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.user')),
            ],
            options={
                'db_table': 'users_history',
            },
        ),
    ]
