# Generated by Django 4.0.5 on 2022-09-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_userhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
