# Generated by Django 4.0.5 on 2022-09-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_user_id_userhistory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
